/*
 * Todo API
 *
 * The Todo API manages a list of todo items as described by the TodoMVC backend project: http://todobackend.com 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package todov1

import (
	"encoding/json"
)

// AddTodoItemRequest struct for AddTodoItemRequest
type AddTodoItemRequest struct {
	Title string `json:"title"`
	Order int32 `json:"order"`
}

// NewAddTodoItemRequest instantiates a new AddTodoItemRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddTodoItemRequest(title string, order int32) *AddTodoItemRequest {
	this := AddTodoItemRequest{}
	this.Title = title
	this.Order = order
	return &this
}

// NewAddTodoItemRequestWithDefaults instantiates a new AddTodoItemRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddTodoItemRequestWithDefaults() *AddTodoItemRequest {
	this := AddTodoItemRequest{}
	return &this
}

// GetTitle returns the Title field value
func (o *AddTodoItemRequest) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *AddTodoItemRequest) GetTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *AddTodoItemRequest) SetTitle(v string) {
	o.Title = v
}

// GetOrder returns the Order field value
func (o *AddTodoItemRequest) GetOrder() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *AddTodoItemRequest) GetOrderOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *AddTodoItemRequest) SetOrder(v int32) {
	o.Order = v
}

func (o AddTodoItemRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["title"] = o.Title
	}
	if true {
		toSerialize["order"] = o.Order
	}
	return json.Marshal(toSerialize)
}

type NullableAddTodoItemRequest struct {
	value *AddTodoItemRequest
	isSet bool
}

func (v NullableAddTodoItemRequest) Get() *AddTodoItemRequest {
	return v.value
}

func (v *NullableAddTodoItemRequest) Set(val *AddTodoItemRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddTodoItemRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddTodoItemRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddTodoItemRequest(val *AddTodoItemRequest) *NullableAddTodoItemRequest {
	return &NullableAddTodoItemRequest{value: val, isSet: true}
}

func (v NullableAddTodoItemRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddTodoItemRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


