run:
    skip-dirs:
        - internal/generated

    skip-files:
        - ".*_gen\\.go$"
        - "^zz_generated\\..*\\.go$"

linters-settings:
    gci:
        sections:
          - standard
          - default
          - prefix(github.com/sagikazarmark/todobackend-go-kit)
    goimports:
        local-prefixes: github.com/sagikazarmark/todobackend-go-kit
    golint:
        min-confidence: 0

linters:
    disable-all: true
    enable:
        - bodyclose
        - dogsled
        - dupl
        - errcheck
        - errorlint
        - exhaustive
        - exportloopref
        - gci
        - gochecknoglobals
        - gochecknoinits
        - gocognit
        - goconst
        - gocritic
        - gocyclo
        - godot
        - gofmt
        - gofumpt
        - goimports
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        # - ifshort
        - ineffassign
        - lll
        - makezero
        - misspell
        - nakedret
        - nilerr
        - nlreturn
        - noctx
        - nolintlint
        - prealloc
        - predeclared
        - revive
        - rowserrcheck
        - sqlclosecheck
        - staticcheck
        - stylecheck
        - thelper
        - tparallel
        - typecheck
        - unconvert
        - unparam
        - unused
        - wastedassign
        - whitespace

        # unused
        # - depguard
        # - goheader
        # - gomodguard

        # don't enable:
        # - asciicheck
        # - exhaustivestruct
        # - forbidigo
        # - funlen
        # - godox
        # - goerr113
        # - gomnd
        # - interfacer
        # - maligned
        # - nestif
        # - paralleltest
        # - testpackage
        # - wrapcheck
        # - wsl
