/*
 * Todo API
 *
 * The Todo API manages a list of todo items as described by the TodoMVC backend project: http://todobackend.com 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package todov1
// TodoItem struct for TodoItem
type TodoItem struct {
	Id string `json:"id"`
	Title string `json:"title"`
	Completed bool `json:"completed"`
	Order int32 `json:"order"`
	Url string `json:"url"`
}
