/*
 * Todo API
 *
 * The Todo API manages a list of todo items as described by the TodoMVC backend project: http://todobackend.com 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package todov1
// AddTodoItemRequest struct for AddTodoItemRequest
type AddTodoItemRequest struct {
	Title string `json:"title"`
	Order int32 `json:"order"`
}
