package(default_visibility = ["PUBLIC"])

#github_repo(
#    name = "go",
#    repo = "simplebuild/please.make",
#    revision = "944dee1",
#)

remote_file(
    name = "go",
    url = "https://raw.githubusercontent.com/simplebuild/please.make/944dee1/.build_defs/make/make-go/make-go.build_defs",
    hashes = [
        "10b73c07b5f6a184c93b5ef66b7f7a014d35b20a",
    ],
)
