name: CI (with Nix)

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: nix develop .#ci -c bash {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Nix
        uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265 # v21
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Nix shell
        run: make versions

      - name: Test
        run: make test

      - name: Annotate tests
        uses: guyarb/golang-test-annotations@9ab2ea84a399d03ffd114bf49dd23ffadc794541 # v0.6.0
        if: always()
        with:
          test-results: build/test.json

  lint:
    name: Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: nix develop .#ci -c bash {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Nix
        uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265 # v21
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Nix shell
        run: make versions

      - name: Lint
        run: make lint
        env:
          LINT_ARGS: --out-format=github-actions
