name: CI (with Nix)

on:
  push:
    branches: [ main ]
  pull_request:

permissions: read-all

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: nix develop .#ci -c bash {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - name: Set up Nix
        uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a # v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Nix shell
        run: echo

      - name: Test
        run: make test

      - name: Annotate tests
        uses: guyarb/golang-test-annotations@9ab2ea84a399d03ffd114bf49dd23ffadc794541 # v0.6.0
        if: always()
        with:
          test-results: build/test.json

  lint:
    name: Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: nix develop .#ci -c bash {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - name: Set up Nix
        uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a # v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Nix shell
        run: echo

      - name: Lint
        run: make lint
        env:
          LINT_ARGS: --out-format=github-actions
