name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

permissions:
  contents: read

jobs:
  artifacts:
    name: Artifacts
    uses: ./.github/workflows/artifacts.yaml
    with:
      publish: true
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ artifacts ]
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # 1.5

      - name: Deploy
        run: flyctl deploy --image ${{ needs.artifacts.outputs.container-image-ref }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
