name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

permissions: read-all

jobs:
  artifacts:
    name: Artifacts
    uses: ./.github/workflows/artifacts2.yaml
    with:
      publish: true
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ artifacts ]
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@adbb124b95f2e47566253d95497432c27f4bdd70 # 1.3

      - name: Deploy
        run: flyctl deploy --image ${{ needs.artifacts.outputs.container-image-ref }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
